const tool=document.querySelector('[data-tool]');
function initTool(type){const r=tool;const wrap=(html,fn)=>{r.innerHTML='<div style="width:100%">'+html+'</div>';fn()};
if(type==='random')wrap('<div class="formgrid"><div><label>Mínimo</label><input id="min" class="input" type="number" value="1"></div><div><label>Máximo</label><input id="max" class="input" type="number" value="100"></div></div><div class="actions"><button id="go" class="btn primary">Generar</button></div><div id="out" class="output center">—</div>',()=>go.onclick=()=>{let a=Number(min.value),b=Number(max.value);if(a>b)[a,b]=[b,a];out.textContent=Math.floor(Math.random()*(b-a+1))+a});
if(type==='color')wrap('<div id="sw" style="height:180px;border-radius:18px;background:#7c5cff"></div><div id="out" class="output center">#7C5CFF</div><div class="actions"><button id="go" class="btn primary">Generar</button><button id="copy" class="btn secondary">Copiar</button></div>',()=>{let hex='#7C5CFF';go.onclick=()=>{hex='#'+Math.floor(Math.random()*16777215).toString(16).padStart(6,'0').toUpperCase();sw.style.background=hex;out.textContent=hex};copy.onclick=()=>navigator.clipboard?.writeText(hex).then(()=>toast('📋 Copiado'))});
if(type==='words')wrap('<textarea id="text" class="textarea" placeholder="Escribe o pega tu texto..."></textarea><div class="statgrid"><div class="stat"><strong id="w">0</strong><span>Palabras</span></div><div class="stat"><strong id="c">0</strong><span>Caracteres</span></div><div class="stat"><strong id="l">0</strong><span>Líneas</span></div><div class="stat"><strong id="s">0</strong><span>Sin espacios</span></div></div>',()=>text.oninput=()=>{const v=text.value;w.textContent=(v.trim().match(/\S+/g)||[]).length;c.textContent=v.length;l.textContent=v?v.split(/\n/).length:0;s.textContent=v.replace(/\s/g,'').length});
if(type==='qr')wrap('<input id="value" class="input" value="https://example.com"><div class="actions"><button id="go" class="btn primary">Generar QR</button></div><div id="qr" class="output center"></div><p class="muted">Requiere conexión para cargar QRCode.js.</p>',()=>{const script=document.createElement('script');script.src='https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js';script.onload=()=>{go.onclick=()=>{qr.innerHTML='';new QRCode(qr,{text:value.value||'NEXO',width:220,height:220})};go.click()};document.body.appendChild(script)});
if(type==='percent')wrap('<div class="formgrid"><div><label>Porcentaje</label><input id="p" class="input" type="number" value="25"></div><div><label>Cantidad</label><input id="n" class="input" type="number" value="200"></div><div><label>Operación</label><select id="m" class="select"><option value="p">Porcentaje</option><option value="d">Descuento</option><option value="a">Aumento</option></select></div></div><div class="actions"><button id="go" class="btn primary">Calcular</button></div><div id="out" class="output center">50</div>',()=>go.onclick=()=>{const b=Number(n.value),x=b*Number(p.value)/100;out.textContent=(m.value==='d'?b-x:m.value==='a'?b+x:x).toFixed(2)});
if(type==='password')wrap('<div class="formgrid"><div><label>Longitud</label><input id="len" class="input" type="number" min="6" max="64" value="16"></div><div><label>Tipo</label><select id="typ" class="select"><option value="all">Todo</option><option value="alnum">Letras + números</option><option value="letters">Solo letras</option></select></div></div><div class="actions"><button id="go" class="btn primary">Generar</button><button id="copy" class="btn secondary">Copiar</button></div><div id="out" class="output center" style="font-family:monospace">—</div>',()=>{function gen(){const set={letters:'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz',alnum:'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789',all:'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*+-_'}[typ.value];let x='';const l=Math.min(64,Math.max(6,Number(len.value)||16));for(let i=0;i<l;i++)x+=set[Math.floor(Math.random()*set.length)];out.textContent=x}go.onclick=gen;copy.onclick=()=>navigator.clipboard?.writeText(out.textContent).then(()=>toast('🔐 Copiada'));gen()});
if(type==='age')wrap('<input id="birth" class="input" type="date"><div class="actions"><button id="go" class="btn primary">Calcular</button></div><div id="out" class="output center">—</div>',()=>go.onclick=()=>{const d=new Date(birth.value+'T00:00:00'),now=new Date();if(!birth.value||d>now){out.textContent='Fecha no válida';return}let y=now.getFullYear()-d.getFullYear(),m=now.getMonth()-d.getMonth(),day=now.getDate()-d.getDate();if(day<0){m--;day+=new Date(now.getFullYear(),now.getMonth(),0).getDate()}if(m<0){y--;m+=12}out.textContent=`${y} años, ${m} meses y ${day} días`});
}
document.addEventListener('DOMContentLoaded',()=>{if(tool)initTool(tool.dataset.tool)})
