/* Islas del Comercio: juego local original, inspirado en juegos de colonización por hexágonos. */
const R=['wood','brick','sheep','wheat','ore'];
const NAMES={wood:'Madera',brick:'Arcilla',sheep:'Lana',wheat:'Trigo',ore:'Mineral'};
const COLORS=['#d84b47','#3879d8','#f0b833','#7d5ac2'];
const app=document.querySelector('#app');
let state={name:'',players:[],tiles:[],verts:[],edges:[],turn:0,setup:[],setupStep:0,phase:'',rolled:false,robber:null,log:[],devDeck:[],winner:null,lastRoll:null};
const rand=a=>a[Math.floor(Math.random()*a.length)];
function initial(){app.innerHTML=`<section class="screen"><div class="card"><h1>Islas <span>del Comercio</span></h1><p class="subtitle">Coloniza, negocia y construye. Una aventura local para tablet, de 3 a 4 jugadores.</p><label class="field">Tu nombre de explorador<input id="username" maxlength="16" placeholder="Ej. Luna" autofocus></label><div class="actions"><button class="primary" id="enter">Entrar al vestíbulo</button></div><p class="note">Proyecto escolar original: funciona en la misma tablet con turnos compartidos. No usa cuentas ni guarda datos.</p></div></section>`;document.querySelector('#enter').onclick=()=>{let n=document.querySelector('#username').value.trim();if(!n)return;state.name=n;lobby()};}
function lobby(){state.players=[{name:state.name,color:COLORS[0]}];renderLobby();}
function renderLobby(){let rows=state.players.map((p,i)=>`<div class="player-row"><i class="dot" style="background:${p.color}"></i><b>${p.name}</b>${i===0?' <small>· anfitrión</small>':''}</div>`).join('');app.innerHTML=`<section class="screen"><div class="card"><h2>Vestíbulo de expedición</h2><p>Invita nombres para una partida local. Pasad la tablet al acabar cada turno.</p><div class="lobby-list">${rows}</div><label class="field">Nombre para invitar<input id="guest" maxlength="16" placeholder="Nombre del siguiente jugador"></label><div class="actions"><button id="add" ${state.players.length>=4?'disabled':''}>Añadir jugador</button><button class="primary" id="start" ${state.players.length<3?'disabled':''}>Comenzar (${state.players.length}/4)</button></div><p class="note">Se necesitan al menos 3 jugadores. La partida termina al llegar a 10 puntos.</p></div></section>`;document.querySelector('#add').onclick=()=>{let n=document.querySelector('#guest').value.trim();if(n&&!state.players.some(p=>p.name.toLowerCase()===n.toLowerCase())){state.players.push({name:n,color:COLORS[state.players.length]});renderLobby()}};document.querySelector('#start').onclick=startGame;}
function startGame(){state.players.forEach(p=>Object.assign(p,{res:Object.fromEntries(R.map(r=>[r,0])),roads:[],buildings:[],dev:[],knights:0,points:0}));makeBoard();const order=[...state.players.keys()];state.setup=[...order,...order.slice().reverse()];state.setupStep=0;state.turn=state.setup[0];state.phase='setup-settlement';state.devDeck=shuffle(['Knight','Knight','Knight','Knight','Knight','Knight','Knight','Knight','Knight','Knight','Knight','Knight','Knight','Knight','Victory','Victory','Victory','Victory','Victory','Roads','Roads','Plenty','Plenty','Monopoly','Monopoly']);state.log=['La expedición comienza. Colocad dos aldeas y sus rutas.'];renderGame();}
function makeBoard(){const types=shuffle(['wood','wood','wood','wood','brick','brick','brick','sheep','sheep','sheep','sheep','wheat','wheat','wheat','wheat','ore','ore','ore','desert']);const nums=shuffle([2,3,3,4,4,5,5,6,6,8,8,9,9,10,10,11,11,12]);const coords=[];for(let r=-2;r<=2;r++)for(let q=Math.max(-2,-r-2);q<=Math.min(2,-r+2);q++)coords.push([q,r]);let vs=new Map(),es=new Map();state.tiles=coords.map((c,i)=>{let [q,r]=c,x=450+70*Math.sqrt(3)*(q+r/2),y=310+105*r,type=types[i],vertices=[];for(let a=0;a<6;a++){let ang=Math.PI/180*(60*a-30),vx=x+70*Math.cos(ang),vy=y+70*Math.sin(ang),key=`${Math.round(vx)},${Math.round(vy)}`;if(!vs.has(key))vs.set(key,{id:vs.size,x:vx,y:vy,owner:null,city:false,tiles:[],edges:[]});let v=vs.get(key);v.tiles.push(i);vertices.push(v.id)}let number=type==='desert'?null:nums.pop();return {id:i,x,y,type,number,vertices,poly:hexPoints(x,y,70)};});state.verts=[...vs.values()];state.tiles.forEach(t=>t.vertices.forEach((a,i)=>{let b=t.vertices[(i+1)%6],key=[a,b].sort((x,y)=>x-y).join('-');if(!es.has(key))es.set(key,{id:es.size,a,b,owner:null});}));state.edges=[...es.values()];state.edges.forEach(e=>{state.verts[e.a].edges.push(e.id);state.verts[e.b].edges.push(e.id)});state.robber=state.tiles.find(t=>t.type==='desert').id;}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
const SYMBOLS={wood:'🌲',brick:'🧱',sheep:'🐑',wheat:'🌾',ore:'⛰️',desert:'🏜️'};
const PIPS={2:1,3:2,4:3,5:4,6:5,8:5,9:4,10:3,11:2,12:1};
function pipMarks(x,y,n){let count=PIPS[n],start=x-(count-1)*4;return Array.from({length:count},(_,i)=>`<circle class="pip" cx="${start+i*8}" cy="${y+10}" r="2.2"/>`).join('')}
function svg(){let t=state.tiles.map(x=>`<g><polygon class="hex ${x.type}" points="${x.poly}" data-tile="${x.id}"/><text class="tile-symbol" x="${x.x}" y="${x.y+55}">${SYMBOLS[x.type]}</text>${x.number?`<circle class="number ${[6,8].includes(x.number)?'hot':''}" cx="${x.x}" cy="${x.y}" r="20"/><text class="num-text" x="${x.x}" y="${x.y-4}">${x.number}</text>${pipMarks(x.x,x.y,x.number)}`:''}${state.robber===x.id?`<text class="robber" x="${x.x-13}" y="${x.y+9}">♟</text>`:''}</g>`).join('');let e=state.edges.map(x=>`<line class="road" data-owner="${x.owner??''}" data-edge="${x.id}" x1="${state.verts[x.a].x}" y1="${state.verts[x.a].y}" x2="${state.verts[x.b].x}" y2="${state.verts[x.b].y}"/>`).join('');let v=state.verts.map(x=>`<circle class="vertex ${x.city?'city':''}" data-owner="${x.owner??''}" data-vert="${x.id}" cx="${x.x}" cy="${x.y}" r="${x.city?12:8}"/>`).join('');return `<svg class="board" viewBox="0 0 900 620" aria-label="Tablero de juego">${t}${e}${v}</svg>`}
function hexPoints(x,y,s){return Array.from({length:6},(_,i)=>{let a=(60*i-30)*Math.PI/180;return `${x+s*Math.cos(a)},${y+s*Math.sin(a)}`}).join(' ')}
function score(p){return p.buildings.reduce((n,id)=>n+(state.verts[id].city?2:1),0)+p.dev.filter(x=>x==='Victory').length+(longestOwner()===state.players.indexOf(p)?2:0)+(armyOwner()===state.players.indexOf(p)?2:0)}
function longestOwner(){let best=-1,own=null;state.players.forEach((p,i)=>{if(p.roads.length>=5&&p.roads.length>best){best=p.roads.length;own=i}});return own}function armyOwner(){let best=-1,own=null;state.players.forEach((p,i)=>{if(p.knights>=3&&p.knights>best){best=p.knights;own=i}});return own}
function panel(){let p=state.players[state.turn],phase=state.phase,actionDev=p.dev.find(x=>x!=='Victory');state.players.forEach(x=>x.points=score(x));return `<aside class="side"><div class="brand">ISLAS <span>IC</span></div><div class="turn-banner"><strong>${p.name} · turno</strong><small>${phase==='setup-settlement'?'Coloca una aldea':phase==='setup-road'?'Conéctala con una ruta':phase==='robber'?'Mueve al bandido a una casilla':state.rolled?'Comercia, construye o termina':'Tira los dados para producir'}</small></div><div><div class="dice">${state.lastRoll?`⚄ ${state.lastRoll}`:'⚄ ⚄'}</div><button class="primary" id="roll" ${state.rolled||phase!=='play'?'disabled':''}>Tirar dados</button> <button id="end" ${!state.rolled||phase!=='play'?'disabled':''}>Terminar turno</button><p class="status">${status()}</p><div class="resource-grid">${R.map(r=>`<div class="res ${r}"><span class="resource-icon"></span><b>${p.res[r]}</b>${NAMES[r]}</div>`).join('')}</div><div class="builds"><button id="road" ${!state.rolled||phase!=='play'?'disabled':''}>Ruta<br><small>Madera + Arcilla</small></button><button id="settle" ${!state.rolled||phase!=='play'?'disabled':''}>Aldea<br><small>M+ A + L + T</small></button><button id="city" ${!state.rolled||phase!=='play'?'disabled':''}>Ciudad<br><small>3 M + 2 T</small></button><button id="dev" ${!state.rolled||phase!=='play'?'disabled':''}>Carta<br><small>M + L + T</small></button><button id="bank" ${!state.rolled||phase!=='play'?'disabled':''}>Banco 4:1</button><button id="trade" ${!state.rolled||phase!=='play'?'disabled':''}>Proponer trato</button></div><p class="tiny">Cartas: ${p.dev.length?p.dev.join(', '):'ninguna'} ${actionDev?`<button id="playdev">Usar ${actionDev}</button>`:''}</p></div><div class="scores"><b>Puntuación</b>${state.players.map((x,i)=>`<div class="score"><span><i class="dot" style="display:inline-block;background:${x.color}"></i> ${x.name}</span><b>${x.points} pts</b></div>`).join('')}</div><div class="log">${state.log.slice(-5).map(x=>`• ${x}`).join('<br>')}</div><button id="help">Reglas rápidas</button></aside>`}
function status(){if(state.phase==='setup-settlement')return 'Haz clic en un cruce libre, sin aldeas vecinas.';if(state.phase==='setup-road')return 'Haz clic en una arista junto a tu aldea nueva.';if(state.phase==='robber')return 'El bandido bloquea esa casilla y roba al azar a un vecino.';return state.rolled?'El tablero está a tu favor.':'Solo quien tira activa la producción.'}
function renderGame(){app.innerHTML=`<div class="game"><section class="board-area">${svg()}</section>${panel()}</div>`;document.querySelector('.board').onclick=e=>{let target=e.target.closest('[data-vert],[data-edge],[data-tile]');if(!target)return;if(target.dataset.vert!==undefined)clickVert(+target.dataset.vert);else if(target.dataset.edge!==undefined)clickEdge(+target.dataset.edge);else clickTile(+target.dataset.tile)};bind();}
function bind(){let q=id=>document.querySelector(id);q('#roll').onclick=roll;q('#end').onclick=end;q('#road').onclick=()=>{state.phase='build-road';renderGame()};q('#settle').onclick=()=>{state.phase='build-settlement';renderGame()};q('#city').onclick=()=>{state.phase='build-city';renderGame()};q('#dev').onclick=buyDev;q('#bank').onclick=bankModal;q('#trade').onclick=tradeModal;q('#help').onclick=help;if(q('#playdev'))q('#playdev').onclick=playDev;}
function clickVert(id){let v=state.verts[id],p=state.players[state.turn];if(['setup-settlement','build-settlement'].includes(state.phase)){if(v.owner!==null||v.edges.some(e=>{let x=state.edges[e];return state.verts[x.a===id?x.b:x.a].owner!==null}))return msg('Ese cruce necesita distancia de otra aldea.');if(state.phase==='build-settlement'&&!canPay(p,{wood:1,brick:1,sheep:1,wheat:1}))return msg('Faltan recursos.');if(state.phase==='build-settlement'&&!v.edges.some(e=>state.edges[e].owner===state.turn))return msg('La aldea debe tocar una ruta tuya.');v.owner=state.turn;p.buildings.push(id);if(state.phase==='build-settlement')pay(p,{wood:1,brick:1,sheep:1,wheat:1});else{state._last=id;if(state.setupStep>=state.players.length)grantSetup(v,p);state.phase='setup-road'}renderGame()}else if(state.phase==='build-city'){if(v.owner!==state.turn||v.city)return msg('Elige una aldea tuya.');if(!canPay(p,{ore:3,wheat:2}))return msg('Faltan recursos.');pay(p,{ore:3,wheat:2});v.city=true;state.phase='play';log(`${p.name} mejora una aldea a ciudad.`);renderGame()}}
function clickEdge(id){let e=state.edges[id],p=state.players[state.turn];if(!['setup-road','build-road'].includes(state.phase)||e.owner!==null)return;if(state.phase==='setup-road'&&!([e.a,e.b].includes(state._last)))return msg('La primera ruta debe tocar la aldea que acabas de colocar.');if(state.phase==='build-road'){let free=state.freeRoads>0;if(!free&&!canPay(p,{wood:1,brick:1}))return msg('Faltan madera y arcilla.');let connected=[e.a,e.b].some(v=>state.verts[v].owner===state.turn||state.verts[v].edges.some(x=>state.edges[x].owner===state.turn));if(!connected)return msg('La ruta debe continuar tu red.');if(free)state.freeRoads--;else pay(p,{wood:1,brick:1})}e.owner=state.turn;p.roads.push(id);if(state.phase==='setup-road'){state.setupStep++;if(state.setupStep<state.setup.length){state.turn=state.setup[state.setupStep];state.phase='setup-settlement'}else{state.turn=0;state.phase='play';state.rolled=false;log('¡Preparación terminada! Empieza el primer turno.')}}else{state.phase=state.freeRoads>0?'build-road':'play';log(`${p.name} construye una ruta.`)}renderGame()}
function clickTile(id){if(state.phase!=='robber'||id===state.robber)return;state.robber=id;let victims=state.players.filter((p,i)=>i!==state.turn&&p.buildings.some(v=>state.verts[v].tiles.includes(id)));if(victims.length){let v=rand(victims),available=R.filter(r=>v.res[r]>0);if(available){let r=rand(available);v.res[r]--;state.players[state.turn].res[r]++;log(`${state.players[state.turn].name} toma 1 recurso de ${v.name}.`)}}state.phase='play';renderGame()}
function roll(){let n=1+Math.floor(Math.random()*6)+1+Math.floor(Math.random()*6);state.lastRoll=n;state.rolled=true;if(n===7){state.players.forEach(p=>{let total=R.reduce((a,r)=>a+p.res[r],0);if(total>7){let loss=Math.floor(total/2);for(let i=0;i<loss;i++){let a=R.filter(r=>p.res[r]>0);p.res[rand(a)]--}log(`${p.name} descarta ${loss} recursos.`)}});state.phase='robber';log('¡7! El bandido entra en juego.')}else{state.tiles.filter(t=>t.number===n&&t.id!==state.robber).forEach(t=>t.vertices.forEach(v=>{let x=state.verts[v];if(x.owner!==null)state.players[x.owner].res[t.type]+=(x.city?2:1)}));log(`Sale ${n}: se reparten los recursos.`)}renderGame()}
function end(){let p=state.players[state.turn];p.points=score(p);if(p.points>=10){state.winner=p;return results()}state.turn=(state.turn+1)%state.players.length;state.rolled=false;state.lastRoll=null;log(`Turno de ${state.players[state.turn].name}.`);renderGame();handoff(state.players[state.turn])}
function handoff(next){let d=document.createElement('section');d.className='handoff';d.innerHTML=`<div class="card"><p class="brand">TURNO PRIVADO</p><h2>Pasa la tablet</h2><p>Ahora juega <b>${next.name}</b>. La mano, las cartas y los recursos de la otra persona están ocultos.</p><button class="primary" id="ready">Ya la tengo · mostrar mi turno</button></div>`;document.body.append(d);d.querySelector('#ready').onclick=()=>d.remove()}
function canPay(p,c){return Object.entries(c).every(([r,n])=>p.res[r]>=n)}function pay(p,c){Object.entries(c).forEach(([r,n])=>p.res[r]-=n)}function log(s){state.log.push(s)}function msg(s){state.log.push(s);renderGame()}
function grantSetup(v,p){v.tiles.forEach(t=>{let r=state.tiles[t].type;if(r!=='desert')p.res[r]++});log(`${p.name} recibe recursos de su segunda aldea.`)}
function buyDev(){let p=state.players[state.turn],cost={ore:1,sheep:1,wheat:1};if(!canPay(p,cost)||!state.devDeck.length)return msg('No hay recursos suficientes o no quedan cartas.');pay(p,cost);let c=state.devDeck.pop();p.dev.push(c);log(`${p.name} obtiene una carta de desarrollo.`);renderGame()}
function playDev(){let p=state.players[state.turn],c=p.dev.find(x=>x!=='Victory');p.dev.splice(p.dev.indexOf(c),1);if(c==='Knight'){p.knights++;state.phase='robber';log(`${p.name} juega un caballero.`);renderGame()}else if(c==='Roads'){state.freeRoads=2;state.phase='build-road';log(`${p.name} puede construir hasta dos rutas gratis.`);renderGame()}else if(c==='Plenty'){resourceChoice('Abundancia: elige dos recursos.',r=>{p.res[r]+=2;log(`${p.name} recibe 2 ${NAMES[r]}.`);renderGame()})}else if(c==='Monopoly'){resourceChoice('Monopolio: elige un recurso.',r=>{let total=0;state.players.forEach(x=>{if(x!==p){total+=x.res[r];x.res[r]=0}});p.res[r]+=total;log(`${p.name} reúne ${total} ${NAMES[r]}.`);renderGame()})}}
function bankModal(){let p=state.players[state.turn];modal(`<h2>Mercado marítimo</h2><p>Entrega 4 unidades de un recurso y recibe 1 de otro.</p><div id="give" class="resource-grid">${R.map(r=>`<button class="${r}" data-r="${r}">${NAMES[r]} (${p.res[r]})</button>`).join('')}</div><p>Recibir:</p><div id="take" class="resource-grid">${R.map(r=>`<button class="${r}" data-r="${r}">${NAMES[r]}</button>`).join('')}</div><div class="actions"><button id="confirm" class="primary" disabled>Intercambiar</button><button id="close">Cancelar</button></div>`,()=>{let g,t;pick('#give',r=>g=r);pick('#take',r=>t=r);document.querySelector('#confirm').onclick=()=>{if(g&&t&&g!==t&&p.res[g]>=4){p.res[g]-=4;p.res[t]++;log(`${p.name} cambia 4 ${NAMES[g]} por ${NAMES[t]}.`);closeModal();renderGame()}else alert('Necesitas 4 unidades y recursos distintos.')}})}
function tradeModal(){let p=state.players[state.turn];modal(`<h2>Trato entre exploradores</h2><p>Elige qué entregas y qué pides. Los jugadores acuerdan el intercambio al pasar la tablet.</p><label class="field">Entregar<select id="g">${R.map(r=>`<option value="${r}">${NAMES[r]} (${p.res[r]})</option>`).join('')}</select></label><label class="field">Recibir<select id="t">${R.map(r=>`<option value="${r}">${NAMES[r]}</option>`).join('')}</select></label><label class="field">Comerciante<select id="who">${state.players.map((x,i)=>i!==state.turn?`<option value="${i}">${x.name}</option>`:'').join('')}</select></label><div class="actions"><button class="primary" id="confirm">Aceptar trato</button><button id="close">Cancelar</button></div>`,()=>document.querySelector('#confirm').onclick=()=>{let g=document.querySelector('#g').value,t=document.querySelector('#t').value,v=state.players[+document.querySelector('#who').value];if(p.res[g]&&v.res[t]){p.res[g]--;v.res[g]++;v.res[t]--;p.res[t]++;log(`${p.name} comercia con ${v.name}.`);closeModal();renderGame()}else alert('Uno de los dos no tiene ese recurso.')})}
function pick(sel,fn){document.querySelectorAll(sel+' button').forEach(b=>b.onclick=()=>{document.querySelectorAll(sel+' button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');fn(b.dataset.r);let a=document.querySelectorAll('#give .selected').length&&document.querySelectorAll('#take .selected').length;document.querySelector('#confirm').disabled=!a})}function modal(html,after){let d=document.createElement('div');d.className='modal';d.innerHTML=`<div class="card">${html}</div>`;document.body.append(d);d.querySelector('#close').onclick=()=>d.remove();window.closeModal=()=>d.remove();after&&after()}
function resourceChoice(title,done){modal(`<h2>${title}</h2><div class="resource-grid">${R.map(r=>`<button class="${r}" data-r="${r}">${NAMES[r]}</button>`).join('')}</div><button id="close">Cancelar</button>`,()=>document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{closeModal();done(b.dataset.r)}))}
function help(){modal(`<h2>Reglas rápidas</h2><div class="help"><p><b>Objetivo:</b> alcanza 10 puntos. Aldea 1, ciudad 2, carta de victoria 1; la ruta más larga y el mayor ejército dan 2.</p><p><b>Dados:</b> toda construcción junto a una casilla con ese número recibe el recurso. Con 7 se descarta la mitad si tienes más de 7 y se mueve el bandido.</p><p><b>Costes:</b> ruta: madera+arcilla; aldea: uno de los cuatro recursos básicos; ciudad: 3 mineral+2 trigo; carta: mineral+lana+trigo.</p><p><b>Diseño:</b> el tablero, nombres y estética son originales y no incluyen contenido, cuentas ni pagos.</p></div><button id="close" class="primary">Entendido</button>`)}
function results(){let ranked=[...state.players].sort((a,b)=>b.points-a.points);app.innerHTML=`<section class="screen"><div class="card"><h1>Fin de la <span>expedición</span></h1><div class="winner">🏆 Gana <b>${state.winner.name}</b> con ${state.winner.points} puntos.</div><h2 style="margin-top:1.4rem">Clasificación</h2>${ranked.map((p,i)=>`<div class="player-row"><b>#${i+1}</b><i class="dot" style="background:${p.color}"></i>${p.name}<strong style="margin-left:auto">${p.points} pts</strong></div>`).join('')}<p class="note">La partida no se ha guardado. Podéis volver a empezar con otros nombres.</p><button class="primary" id="again">Volver al menú</button></div></section>`;document.querySelector('#again').onclick=()=>{state={name:'',players:[],tiles:[],verts:[],edges:[],turn:0,setup:[],setupStep:0,phase:'',rolled:false,robber:null,log:[],devDeck:[],winner:null,lastRoll:null};initial()}}
initial();
