const TESTS={
 personalidad:{title:'¿Qué personalidad tienes?',questions:[['En un plan con amigos prefieres…','Organizarlo todo','Improvisar sobre la marcha','Disfrutar sin prisas'],['Cuando aparece un problema…','Busco una solución lógica','Me adapto rápido','Pido opiniones antes de decidir'],['Tu reto ideal es…','Superar una meta difícil','Vivir algo nuevo','Compartirlo con gente cercana'],['¿Qué valoras más?','La disciplina','La libertad','La conexión con los demás']],results:{A:['🧭','Estratega','Eres una persona enfocada, constante y con facilidad para convertir ideas en planes.'],B:['⚡','Explorador','Te mueven la curiosidad, la acción y descubrir experiencias nuevas.'],C:['🤝','Conector','Tu fortaleza es entender a los demás y crear buen ambiente.']}},
 futbolista:{title:'¿Qué futbolista eres?',questions:[['En un partido, tu mejor cualidad sería…','Leer el juego','Desbordar a un rival','Animar al equipo'],['Cuando tu equipo pierde…','Analizo qué cambiar','Busco una jugada decisiva','Mantengo la calma'],['Tu estilo de juego es…','Preciso y técnico','Rápido y atrevido','Generoso y colectivo'],['Eliges una posición…','Centrocampista','Extremo','Delantero'],['Tu objetivo principal es…','Controlar el partido','Crear espectáculo','Ayudar a ganar']],results:{A:['🎯','Kevin De Bruyne','Visión, precisión y calma: haces mejor a todo el equipo.'],B:['⚡','Kylian Mbappé','Velocidad, valentía y hambre de gol. Siempre buscas la jugada grande.'],C:['🏆','Lionel Messi','Talento, creatividad y una forma de jugar que conecta con los demás.']}},
 videojuego:{title:'¿Qué videojuego encaja contigo?',questions:[['Buscas sobre todo…','Resolver retos','Competir y reaccionar','Vivir una historia'],['Tu partida ideal dura…','Lo que haga falta','Partidas rápidas','Una tarde tranquila'],['Te atrae más…','Construir una estrategia','Dominar mecánicas','Explorar un mundo'],['Al perder una partida…','Cambio de plan','Vuelvo inmediatamente','Me tomo un descanso']],results:{A:['🧠','Civilization VI','Te gustan los retos con estrategia, decisiones y planes a largo plazo.'],B:['🎮','Rocket League','Competición, reflejos y mejora constante: perfecto para ti.'],C:['🌄','The Legend of Zelda','Quieres descubrir mundos, historias y secretos a tu ritmo.']}},
 pais:{title:'¿Qué país deberías visitar?',questions:[['Tu viaje ideal incluye…','Cultura y museos','Naturaleza y aventura','Comida y vida urbana'],['Prefieres moverte…','Con un itinerario claro','Sin demasiados planes','Descubriendo barrios'],['El clima perfecto es…','Templado','Fresco y de montaña','Cálido'],['Una foto de viaje sería…','Un templo histórico','Un paisaje enorme','Una calle llena de vida']],results:{A:['🇯🇵','Japón','Te encajaría su mezcla de historia, tecnología y detalle.'],B:['🇮🇸','Islandia','Naturaleza espectacular y aventura: justo tu tipo de viaje.'],C:['🇮🇹','Italia','Arte, energía urbana y una gastronomía para disfrutar sin prisa.']}},
 coche:{title:'¿Qué coche te representa?',questions:[['Tu prioridad al conducir es…','Precisión','Potencia','Comodidad'],['Un coche debe destacar por…','Tecnología','Diseño deportivo','Espacio y estilo'],['Tu ruta favorita tiene…','Curvas técnicas','Carretera abierta','Paradas bonitas'],['Ante una compra eliges…','La opción más equilibrada','La más emocionante','La más práctica']],results:{A:['🚘','Tesla Model 3','Eres moderno, eficiente y te gusta que la tecnología tenga propósito.'],B:['🏎️','BMW M4','Te motiva la energía, el diseño y sentir cada momento.'],C:['🚙','Volvo XC60','Valoras seguridad, comodidad y experiencias compartidas.']}},
 pelicula:{title:'¿Qué película encaja contigo?',questions:[['Quieres que una película te haga sentir…','Asombro','Adrenalina','Emoción'],['Tu protagonista ideal es…','Alguien ingenioso','Alguien valiente','Alguien cercano'],['El final perfecto es…','Que te haga pensar','Que te deje sin aliento','Que te toque el corazón'],['Eliges una tarde de cine con…','Una historia compleja','Acción sin pausa','Una historia humana']],results:{A:['🌌','Interstellar','Te fascinan las historias grandes que invitan a pensar.'],B:['🕶️','Mad Max: Fury Road','Buscas intensidad, ritmo y una aventura que no frene.'],C:['🎈','Up','Conectas con historias cálidas, memorables y llenas de corazón.']}}
};
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function startTest(root,slug){const data=TESTS[slug];if(!root||!data)return;let i=0,score={A:0,B:0,C:0};const render=()=>{const q=data.questions[i];root.innerHTML='<div style="width:100%"><div class="quizmeta"><span>'+data.title+'</span><span>'+(i+1)+'/'+data.questions.length+'</span></div><div class="card"><h2>'+q[0]+'</h2><div class="choicegrid">'+q.slice(1).map((text,n)=>'<button class="choice" data-k="'+String.fromCharCode(65+n)+'">'+escapeHtml(text)+'</button>').join('')+'</div></div></div>';root.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{score[b.dataset.k]++;i<data.questions.length-1?(i++,render()):finish()})};const finish=()=>{const key=Object.keys(score).sort((a,b)=>score[b]-score[a])[0],r=data.results[key],s=NexoStore.loadState();s.stats.gamesPlayed++;NexoXP.giveXP(s,'game');const got=NexoAch.checkAchievements(s);NexoStore.saveState(s);root.innerHTML='<div class="card center"><div class="icon">'+r[0]+'</div><h2>'+r[1]+'</h2><p>'+r[2]+'</p><button id="again" class="btn primary">Repetir test</button></div>';toast('🎯 Test completado · +25 XP');got.forEach(x=>setTimeout(()=>toast('🏅 '+x),150));root.querySelector('#again').onclick=()=>startTest(root,slug)};render()}
window.NexoTest={startTest};
document.addEventListener('DOMContentLoaded',()=>{const root=document.querySelector('[data-test]');if(root)startTest(root,root.dataset.test)});
